name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: pip install poetry==1.8.2

    - name: Install dependencies
      run: poetry install --no-root

    - name: Run tests
      run: make test

    - name: Run linting
      run: make lint

    - name: Run type checking
      run: make typecheck